name: Pregunta Examen3
on: [push]
jobs:
  print-information:
    runs-on: ubuntu-latest
    steps:

    - name: Print Name
      run: echo "Mi nombre completo es: Fernando De Santos Franco"

    - name: Print Node.js Version
      run: node -v

    - name: Print Expediente
      run: echo "Mi expediente es: 731142"